### ISSUE TITLE
Gruppe logo

### ISSUE THREAD

**Issue by Zenjjim** [TIHLDE/Kvark#108]
![image](https://user-images.githubusercontent.com/23628986/117656242-67d3a100-b198-11eb-9910-3e33febc505f.png)

Flere grupper har egen logo og kult om dette blir vist på både gruppeoversikt og mine grupper :D

**Comment by olros** [comment]
Må legges til bildeopplastning i "Rediger gruppe". Foreslår at vi setter ratio på bilde til "1 / 1", altså kvadratisk
