### ISSUE TITLE
Fondet link broken

### ISSUE THREAD

**Issue by antontveito** [TIHLDE/Kvark#1081]
### What happened?

A bug happened! There is no href.
<img width="1322" alt="Skjermbilde 2024-09-16 kl  19 11 18" src="https://github.com/user-attachments/assets/20c4247d-e614-46b8-a93f-c13eee85a859">

### What browsers are you seeing the problem on?

Chrome

### What device are you seeing the problem om?

PC

**Comment by Embretr** [comment]
Din idiot! Dette er ikke hardkodet inn i kvark, men ligger som beskrivelse på hver gruppe i databasen.
