### ISSUE TITLE
Can't change profile pictures as admin

### ISSUE THREAD

**Issue by antontveito** [TIHLDE/Kvark#1082]
### What happened?

A bug happened! I can't upload pictures to profiles.

### What browsers are you seeing the problem on?

Chrome, Safari

### What device are you seeing the problem om?

Mobile, PC

**Comment by Embretr** [comment]
Great issue @antontveito. As you have encountered it, i think you should be the one to fix it.

**Comment by AleksanderEvensen** [comment]
Looks like the User edit form re-renders every second when you expand the profile. This moste likely causes the imageFile state to be cleared, and therefor no image will be uploaded to the server.
There is also some unlabled form fields I don't know if react-form-hook causes these re-renders.
<img width="771" alt="image" src="https://github.com/user-attachments/assets/d1de22bc-5e1a-4290-8485-ec3719a03940">

**Comment by Embretr** [comment]
@antontveito hurry up
