### ISSUE TITLE
Markdown Editor

### ISSUE THREAD

**Issue by MadsNyl** [TIHLDE/Kvark#1086]
### Refactor suggestion

Our Markdown editor should be rich.

As an admin I want it to be easier to write markdown with menu buttons for header, bold text etc. 

Github's markdown editor is a good and simle example.

**Comment by Embretr** [comment]
I suggest we then do markdown only under the hood, like here:

https://mdxeditor.dev/

I have used it before, and it's nice.

**Comment by Embretr** [comment]
I will close this issue, and group it with the other markdown issue, as one should fix both at the same time.
