### ISSUE TITLE
Prikker

### ISSUE THREAD

**Issue by Zenjjim** [TIHLDE/Kvark#109]
Ettersom prikker er så og si fullført i backend trengs det et sted for:

- [ ] Å ha oversikt over alle sine prikker (for admin)
- [ ] Ha oversikt over mine prikker
- [ ] Et sted for admin å lage prikker
- [ ] Wall of shame 👿

**Comment by Zenjjim** [comment]
Ved opprettelse av prikker kan man enten lage egen beskrivelse og sende med størrelse. Men kan også sende [prikkenum](https://github.com/TIHLDE/Lepton/blob/5e56ec20de0bac293620228a5f8ad26def5114b6/app/common/enums.py#L92)

**Comment by Eirsteir** [comment]
Bør være mulig å sende med arrangement også ved opprettelse av prikker

**Comment by olros** [comment]
Delt opp i mindre issues:

- #222 
- #223 
- #224
