### ISSUE TITLE
Digsam On "For Bedrifter" Page

### ISSUE THREAD

**Issue by MadsNyl** [TIHLDE/Kvark#1090]
### What happened?

The section about Digial Transformasjon study at the page "For Bedrifter" shows Digital Samhandling. This must be changed

### What browsers are you seeing the problem on?

Chrome

### What device are you seeing the problem om?

PC

**Comment by Embretr** [comment]
Anton has a fix for this already, but he needs to fix the merge conflicts before we merge it, and we must double check that he hasnt switched any of the links as well.

**Comment by Embretr** [comment]
@antontveito we will fix it together during the meeting
