### ISSUE TITLE
Profile page icons on mobile

### ISSUE THREAD

**Issue by MadsNyl** [TIHLDE/Kvark#1116]
### Refactor suggestion

The icons for the different sections on user profile is too small when the text is too long on mobile. These icons and maybe text should be smaller on mobile.

![image](https://github.com/user-attachments/assets/bc29d2ba-8b5d-4ade-b526-44fdd90cc169)

**Comment by Ananta2003** [comment]
@MadsNyl Is anyone working on this issue?
