### ISSUE TITLE
Says you will get one "prikk" when deregistrating before the deadline

### ISSUE THREAD

**Issue by antontveito** [TIHLDE/Kvark#1120]
### What happened?

Says you will get one "pikk", although you dont get one, because you are deregistrating before the deadline. This bug should be fixed.
<img width="1097" alt="Skjermbilde 2024-10-01 kl  11 13 43" src="https://github.com/user-attachments/assets/f69a94d9-ab04-4bbf-9bfa-7e80444a3e09">

### What browsers are you seeing the problem on?

Chrome

### What device are you seeing the problem om?

PC

**Comment by Embretr** [comment]
Følg med a anton. Denne er merget inn i dev.

**Comment by Embretr** [comment]
Har ikke mista merge inn i prod jomfrudommen enda😫 Så må ha litt hjelp av mads
