### ISSUE TITLE
Kokeboka admin

### ISSUE THREAD

**Issue by olros** [TIHLDE/Kvark#116]
Lag admin-muligheter for kokeboka på nettsiden.

Admins skal kunne legge til, endre og slette alle kok.
Vanlige brukere skal kunne laste opp, endre og slette egne kok. (Kan diskuteres, men jeg tror det er beste løsningen for å få mer innhold i kokeboka).

Bør nok sees i sammenheng med #33 og #98

**Comment by magsteen** [comment]
Må passe på med å legge inn begrensning også så ikke hvem som helst kan legge alt mulig rart. Kanskje at ting må godkjennes av en admin eller no før det blir ordentlig lagt til?
