### ISSUE TITLE
Markdown editor forbedring

### ISSUE THREAD

**Issue by olros** [TIHLDE/Kvark#117]
Markdown editoren bør utvides med støtte for flere "hurtighandlinger" som hjelper brukerne i å lage diverse innhold i markdown. Eksempler på dette er:

- **Filopplastning** som returnerer markdown-string for bilde der bilde-url er til opplastet bilde.
- **Arrangement**-kort innsetter som tar input event-id og returnerer markdown kode. Tilsvarende for annonser og nyheter.
- **Utvid-boks** generator der du kan lage utvid-bokser visuelt med innhold og til slutt returnerer tilsvarende i markdown
- **Link**. Skriv inn link og linktekst og få markdown i retur
- **Forhåndsvisning**. Mulighet til å forhåndsse hvordan innholdet vil bli rendret uten at man må se det gjennom for eksempel forhåndsvisning av hele arrangementet.

Layout her kan for eksempel være som i github med "Skriv" og "Forhåndsvis"-tabs, samt knapper for filopplastning, link, osv...:
![image](https://user-images.githubusercontent.com/31009729/125081177-ffd10680-e0c5-11eb-989a-28866b37ceac.png)

**Comment by Zenjjim** [comment]
En ide kan være https://github.com/ianstormtaylor/slate
