### ISSUE TITLE
[Feature]: klikkbart banner 

### ISSUE THREAD

**Issue by Eirsteir** [TIHLDE/Kvark#144]
### Feature request

Som admin ønsker jeg å kunne lage et banner på forsiden med tekst som brukerne kan klikke på for mer informasjon slik at jeg enkelt kan formidle ting til brukerne. 

Dette kan feks løses ved å lage nye komponenter og legge inn en løsning i backend eller gjøre warnings klikkbare. Ulempen med sistnevnte er at disse forsvinner når man krysser dem ut

**Comment by olros** [comment]
Warnings er klikkbare per dags dato, de støtter markdown formatering som betyr at du kan legge inn for eksempel linker. Spørs om det holder for formålet da

**Comment by Eirsteir** [comment]
Typ sånn «interresert i verv i tihlde? Klikk her» og kan være dumt at warnings forsvinner. Slik som infoboksen vi hadde for nye studenter hadde vært et godt use-case
