### ISSUE TITLE
[Feature]: Tooltips

### ISSUE THREAD

**Issue by Eirsteir** [TIHLDE/Kvark#145]
### Feature request

For å gjøre nettsiden enklere å sette seg inn i og bruke, da spesielt for admins, kan det være greit med tooltips som hjelper brukeren med å komme i gang. En tooltip gir brukeren mer informasjon om en handling feks når man hoovrer over den.

For eksempel kan det være en tooltip på å krysse av for ankomst for en påmeldt.

Det kan også brukes for å showcase nye features.

Noen eksempler:

![](https://i.stack.imgur.com/eZTqB.png)

![](https://editorjs.io/uploads/33a9f9bb7ecbcd8a9f793f923b8d8e2a.png)

**Comment by trthingnes** [comment]
Burde vi splitte dette i to?
