### ISSUE TITLE
Ikke tillatt brukere å melde seg på bedpres/kurs hvis de ikke har svart på evalueringsskjemaet

### ISSUE THREAD

**Issue by Eirsteir** [TIHLDE/Kvark#162]
### Feature request

Det er hensiktsmessig å ikke tillate brukere å trykke på "Meld deg på"-knappen på en bedpres/kurs når de ikke har svart på evalueringsskjemaet for et tidligere et. Knappen kan feks disables.

Dette bør bli sendt med som et felt fra backend og koordineres med TIHLDE/Lepton#185.

**Comment by Eirsteir** [comment]
@olros denne er ferdig, ikke sant?

**Comment by olros** [comment]
Ja det skal den være, closer 👍
