### ISSUE TITLE
Brukerteste pages 🚀 

### ISSUE THREAD

**Issue by Eirsteir** [TIHLDE/Kvark#182]
Vi har fått tilbakemeldinger på at pages (wiki/om TIHLDE) kan være kronglete og lite brukervennlig, så vi må kjøre noen brukertester for å kartlegge eventuelle forbedringer og mangler. 

Vi bør bli flinkere generelt på å gjennomføre brukertester på nye features for å løfte løsningene våre opp enda noen hakk så vi alltid kan tilby den best mulige brukeropplevelsen. 

Det kan være greit å lage en mal for brukertestene i slab og kjøre den samme på alle vi intervjuer. Da får vi også et grunnlag for å kjøre flere brukertester på andre områder.

**Comment by olros** [comment]
Anser denne som ikke lenger relevant. Har fått tilbakemeldinger på at wiki'en nå er blitt betydelig lettere å bruke.

Brukertesting generelt er fremdeles veldig lurt!
