### ISSUE TITLE
Søknadsskjema for nye komiteer 

### ISSUE THREAD

**Issue by Eirsteir** [TIHLDE/Kvark#191]
### Feature request

**Som bruker ønsker jeg å sende inn et søknadsskjema for å opprette en ny komité til HS slik at jeg enkelt kan opprette en ny en.**

**Som HS-medlem ønsker jeg at brukere skal kunne sende inn søknader til styret som jeg kan godkjenne/avslå slik at terskelen for å opprette nye komitéer senkes**

**Som bruker/HS-medlem ønsker jeg at den nye komitéen skal opprettes automatisk på nettsiden når søknaden blir godkjent.**

**Comment by martcl** [comment]
Dette er en funksjonalitet som finnes i gruppeskjemaer
