### ISSUE TITLE
Skjema-mal (form templates)

### ISSUE THREAD

**Issue by Eirsteir** [TIHLDE/Kvark#194]
### Feature request

**Som admin ønsker jeg å kunne lage og bruke en template for skjemaer slik at jeg slipper å lage et nytt skjema hver gang**

Et template er et predefinert skjema som kan gjenbrukes i flere sammenhenger.

Templaten kan hentes ut fra backend vha filtrering og kunne sendes tilbake som et "nytt" skjema, altså lages det en duplikat av templaten. Dette er for at ikke alle svar på dette skjemaet vil tilknyttes templaten.

**Comment by olros** [comment]
Forslag:

Legg listen med Templates under "Opprett skjema". Da blir det også enklere å lage en "slette"-knapp som setter "template: false"
