### ISSUE TITLE
Bytt ut Redux med useContext

### ISSUE THREAD

**Issue by Zenjjim** [tihlde/Kvark#196]
Erstatt all redux funksjonalitet og erstatt den med useContext

**Comment by maxschau** [comment]
Er det tatt stilling til hvorvidt man skal bruke useReducer vs useContext?

**Comment by olros** [comment]
> Er det tatt stilling til hvorvidt man skal bruke useReducer vs useContext?

Så ikke denne før nå, men sånn jeg har sett andre gjøre det er med begge deler. Se eksempel i pr'en. Bruker 2 contexter per "store": 1 for reduceren og 1 for selve staten. Da er det enkelt hente spesifikt reduceren som igjen oppdaterer staten for oss. useReducer i seg selv kan ikke holde på en global state, den gir oss bare hjelpefunksjoner som gjør det enkelt å oppdatere state'en.
