### ISSUE TITLE
Refaktorere til react-hook-form

### ISSUE THREAD

**Issue by Zenjjim** [tihlde/Kvark#197]
Bytte om alle form til [react-hook-form](https://react-hook-form.com/) for bedre feil-håndtering og finere kode.
- [ ] Lage globale form komponenter som blir gjenbrukt som f.eks. datepicker, mail, input, dropdown osv. Lage disse så dumme som mulig.
- [ ] Lage dumme form komponenter (input, checkbox, numberinput og evt andre)

**Comment by olros** [comment]
Ferdig sammen med konvertering til typescript. #405 fikser en liten resterende del
