### ISSUE TITLE
Legg til bilde prop i MessageIndicator

### ISSUE THREAD

**Issue by Zenjjim** [tihlde/Kvark#198]
@olros forklar gjerne mer her

**Comment by olros** [comment]
`<MessageIndicator />` brukes i `NoEventsIndicator`, `NoNewsIndicator`, `NoPersonsIndicator` og `NoPostsIndicator` på samme måte med et bilde over den. En bedre løsning er å legge inn mulighet til å sende inn et bilde til `<MessageIndicator img={img} />` så vi kan fjerne nevnte `NoEventsIndicator`, `NoNewsIndicator`, `NoPersonsIndicator` og `NoPostsIndicator` og kun bruke `MessageIndicator`.
