### ISSUE TITLE
Bytt ut markdown-editor

### ISSUE THREAD

**Issue by Zenjjim** [tihlde/Kvark#207]
Vurder å bytt ut markdown editoren med for eks:
- https://harrychen0506.github.io/react-markdown-editor-lite/
- https://github.com/uiwjs/react-md-editor

**Comment by olros** [comment]
Tanke om å bare bruke Material UI sitt Textarea uten å ha en toolbar for overskrift, bold, italic, link, osv. Men heller legge ved en popup som forklarer hvordan markdown fungerer og hva man kan skrive inn for å lage diverse elementer?

Det løser 2 ting:
- Darkmode
- Kan fjerne stor dependency

@tihlde/index
