### ISSUE TITLE
Gjøre det mulig for HS å endre hvilken undergruppe du er på

### ISSUE THREAD

**Issue by Zenjjim** [tihlde/Kvark#211]
Brukerstory:
Som HS ønsker jeg å kunne endre TIHLDE-medlemmer sin gruppestatus, slik at ved opptak kan jeg legge til nye tihlde-medlemmer i sine respektive grupper. Dette må til slik at f.eks. nok skal ha tilgang til å lage jobbannonser.

Frontend:
Admin panel der admin kan sortere på gruppe og se alle medlemmer til den respektive gruppen. Admin skal også ha tilgang til å legge til og fjerne medlemmer fra gruppen slik den ønsker.

**Comment by Eirsteir** [comment]
Lukker pga #246
