### ISSUE TITLE
Ukens bedrift 

### ISSUE THREAD

**Issue by olros** [TIHLDE/Kvark#23]
Lag et admin-panel der nok, index og hs kan legge til ukens bedrifter. Man må kunne se en oversikt over de kommende bedriftene, redigere, slette og opprette nye.

Ukens bedrift skal vises på forsiden øverst. Enten der det er en TIHLDE-logo nå, eller som en boks mellom bølgene og "Siste".

![image](https://user-images.githubusercontent.com/31009729/110234517-3980dd80-7f2b-11eb-92a6-f9e8e2b58c3a.png)

**Comment by Eirsteir** [comment]
Denne skal ikke ligge på forsiden, men på en egen side + en plass i nav-baren @olros

**Comment by Eirsteir** [comment]
Den likte jeg godt, da blir den synlig og lett tilgjengelig både på PC og mobil uten å ta over hele forsiden 👍
