### ISSUE TITLE
Ingen word wrap på spørsmål i forms

### ISSUE THREAD

**Issue by thomsen85** [TIHLDE/Kvark#230]
### What happened?

![image](https://user-images.githubusercontent.com/13613544/136051209-311b4db2-9fac-424f-9077-b54487feea6a.png)

### What browsers are you seeing the problem on?

Chrome

### What device are you seeing the problem om?

PC

**Comment by olros** [comment]
For å fikse dette kan vi flytte label i forms ut av TextField og til å stå over TextField slik som på flervalgsknappene.

Når du først er i gang så kan vi også legge til `multiline`-prop'en på TextField's i Forms slik at man lettere kan skrive lengre svar.
