### ISSUE TITLE
Refactor to typescript

### ISSUE THREAD

**Issue by olros** [tihlde/Kvark#243]
https://github.com/typescript-cheatsheets/react

## Hvordan skal filene lagres?
Alle filer skal lagres som .tsx fil. 

## Hvordan definerer vi props-typer til en komponent?
De fleste komponenter har en eller annen form for props. I TypeScript ønsker vi at vi skal definere hvilke typer disse skal være. 

Vi lagrer de ulike propsene i et objekt som i eksempelet under kalles for CardType. Først skriver man navnet på selve propen, og deretter skriver du : datatypen. Dette kan være string, number, string[], osv. Her kan man også bruke egendefinerte interface om det skulle være nødvendig. 
![image](https://user-images.githubusercontent.com/31009729/94453262-c1123580-01b0-11eb-8a29-1403f559220f.png)

Hadde man nå prøvd å benyttet card-komponenten med feiltype vil dette gi en feilmelding ettersom man forsøker å sende inn et heltall når headline er satt til å være string. 
![image](https://user-images.githubusercontent.com/31009729/94453298-ccfdf780-01b0-11eb-976c-2b37ddc97c04.png)

## Checklist
- All relative imports should be converted to absolute imports
- All HOC's should be replaced with Hooks
- Use theme.spacing() instead of custom padding
- Use theme.breakpoints instead of custom media queries

## Material UI tips:
- Padding og margin:
  - `padding: '0 8px'` -> `padding: theme.spacing(0, 1)`
  - `0 - 5` -> 0
  - `6 - 12` -> 1
  - `13 - 19` -> 2
  - osv...
- Media queries:
  - `@media only screen and (max-width = 600px)` -> `[theme.breakpoints.down('xs')]`
  - `max-width = 900px` -> `[theme.breakpoints.down('sm')]`
  - `max-width = 1200px` -> `[theme.breakpoints.down('lg')]`
- Typography (som oftest):
  - `h3` -> `h1`
  - `h4` -> `h1` eller `h2`
  - `h5` -> `h2` eller `h3`
  - `h6` -> `h3`

**Comment by olros** [comment]
Jeg tar **Navigation**:
- [ ] Dialog.js
- [ ] Footer.js
- [ ] Link.js
- [ ] LinkButton.js
- [ ] Navigation.js
- [ ] Sidebar.js
- [ ] Snack.js

**Comment by Her0elt** [comment]
Jeg tar layout mappen

**Comment by maxschau** [comment]
Jeg tar miscellaneous

- [ ] ClickableImage.js
- [ ] DropdownButton.js
- [ ] Emoji.js
- [ ] ListItem.js
- [ ] MarkdownRenderer.js
- [ ] MessageGDPR.js
- [ ] ThemeSettings.js

**Comment by olros** [comment]
Tar **/api** :

- [ ] api.js
- [ ] auth.js
- [x] cookie.ts
- [ ] httphandler.js

**/api/hooks**:
- [ ] News.js

**/api/services**:
- [ ] AuthService.js
- [ ] BadgeService.js
- [ ] CheatsheetService.js
- [ ] EventService.js
- [ ] JobPostService.js
- [ ] MiscService.js
- [ ] NotificationService.js
- [ ] UserService.js

**Comment by olros** [comment]
Holder på med Cheatsheet og har gjort EventRegistration

**Comment by olros** [comment]
Tar EventDetails, Events, og EventAdministration

**Comment by Her0elt** [comment]
tar UserAdmin
