### ISSUE TITLE
Egenbestemt sortering i forms

### ISSUE THREAD

**Issue by olros** [TIHLDE/Kvark#249]
### Feature request

Som admin ønsker jeg å kunne bestemme rekkefølgen på spørsmål og alternativ i forms. Dette løses gjennom https://github.com/TIHLDE/Lepton/pull/285 ved at hvert `field` og `option` har et `order`-felt som da vil brukes for sortering.
Det som må gjøres er:

- Legge til at det sendes en `order` til backend
- Finne et godt bibliotek for "drag-and-drop" slik at admins kan endre rekkefølgen på spørsmålene. Bør være fleksibelt slik at det også potensielt kan brukes i pages også

**Comment by martcl** [comment]
## Funnet noen alternativ
1. [sortablejs](https://github.com/SortableJS/Sortable). Min nummer 1! Demoene som ligger lenket til på Githuben er veldig fine, og de sier at den funker fint på mobil. I tillegg er det veldig mange som bruker denne pakken, men ikke like mange som de nevnt under.
2. [react-dnd](https://github.com/react-dnd/react-dnd). Et prosjekt som ser ut til å ha en stor brukerbase og mange contributors. Akkurat nå ser det ut som om det er en hovedperson som styrer prosjektet. Vil tro at prosjektet fortsetter å fikse bugs og utvikle seg. Dette er førstevalget:)
3. [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd). Er veldig populært men sier "no current plans for further feature development or improvements", noe som gjør denne pakken dårlig egnet.

Det finnes også mange andre prosjekter som det går ann å bruke men jeg er ganske sikker på at nr. 1 vil funke helt fint. Hentet blant annet informasjon om pakker her https://openbase.com/categories/js/best-react-drag-and-drop-libraries

**Comment by olros** [comment]
Det er viktig å tenke på størrelsen på pakken slik at vi ikke legger til for store dependencies. Du kan bruke bundlephobia for å sjekke det. I tillegg må du sjekke hvor lett det er å bruke det med React. Slikt som sortablejs er ikke nødvendigvis lett å bruke med react ut av boksen, og https://www.npmjs.com/package/react-sortablejs står at den ikke er klar for produksjon
