### ISSUE TITLE
Bytt ut Moment med Date-fns

### ISSUE THREAD

**Issue by olros** [tihlde/Kvark#255]
Moment er utdatert, tungt og ikke lenger anbefalt, mens Date-fns er bedre og mer lightweight.

https://date-fns.org/docs/Getting-Started

**Comment by MathiasWP** [comment]
Tips: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat.
Mer vanilla/lightweight blir det ikke ;)

**Comment by olros** [comment]
> Tips: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat.
> Mer vanilla/lightweight blir det ikke ;)

Sant nok, men trenger litt mer enn bare formatering av dato.
