### ISSUE TITLE
Gi admins og devkom tilgang til epostene til de påmeldte til et arrangement 

### ISSUE THREAD

**Issue by Eirsteir** [tihlde/Kvark#258]
Prosessen for å sende en infomail til påmeldte brukere til et arrangement er nokså tungvint per i dag og vi ønsker å forenkle prosessen. I første omgang holder det med en knapp som kopierer alle epostene til clipboardet. 

User-story: Som admin og medlem av devkom ønsker jeg å kunne kopiere alle epostene til påmeldte brukere så jeg kan manuelt sende dem en e-post.

Når grupper og medlemskap blir implementert skal også leder av undergruppe kunne gjøre dette. 

På sikt skal dette automatiseres i backend, slik at man kun trenger å skrive en melding i admin-siden som blir sendt ut som notifikasjon og e-post til alle påmeldte.

**Comment by olros** [comment]
Backend sender ikke ut epost i events/<id>/users så det må gjøres først

![image](https://user-images.githubusercontent.com/31009729/95836690-09e4f500-0d40-11eb-9244-688a1aaa6985.png)
