### ISSUE TITLE
Gjør cookie consent lovlig

### ISSUE THREAD

**Issue by norgor** [TIHLDE/Kvark#269]
Cookie-consenten vår er ikke i henhold til nåværende retningslinjer og må oppdateres.

**Comment by olros** [comment]
Kan du utdype hva som ikke er lovlig? Kan vi evt gjøre som nrk.no og legge info i footer

![Screenshot_20211102-165004_Chrome](https://user-images.githubusercontent.com/31009729/139883863-c16ee615-57ef-40b9-b400-8bb39093f660.jpg)

**Comment by norgor** [comment]
Jepp!
> § 2-7b Bruk av informasjonskapsler/cookies
>
> Lagring av opplysninger i brukers kommunikasjonsutstyr, eller å skaffe seg adgang til slike, er ikke tillatt uten at brukeren er informert om hvilke opplysninger som behandles, formålet med behandlingen, hvem som behandler opplysningene, og har samtykket til dette.

Man må altså spør brukeren om samtykke og la brukeren trekke tilbake samtykket sitt på senere tidspunkt.

**Comment by olros** [comment]
Flere andre store statlige/proffe nettsider opererer på samme måte som oss:

- https://www.regjeringen.no/no/om-nettstedet/personvernerklaring/id650340/#tocNode_9
- https://www.politiet.no/personvern-og-informasjonskapslar/
- https://www.forbrukerradet.no/personvernerklaering/
- https://stortinget.no/no/Stottemeny/Hjelp/Om-nettstedet/Personvernerklaring-Stortinget/
- https://lovdata.no/info/personvern#cookies

Foreslår derfor at vi lukker dette issuet ettersom Google Analytics er såpass nyttig ift å lære hva som funker og ikke funker.
