### ISSUE TITLE
Botsystem for grupper

### ISSUE THREAD

**Issue by olros** [TIHLDE/Kvark#272]
### Feature request

Flere grupper har et eget internt botsystem. Hvis vi lager et eget vil det bli større aktivitet på nettsiden og større intensiv for å holde gruppene oppdatert. Foreslåtte features:

- Alle kan legge til bøter på andre gruppemedlemmer i grupper de er medlem av
- Bøter er i utgangspunktet ikke "godkjent", men kan bli godkjent av leder i gruppen. Hvordan bøter godkjennes blir opp til gruppen selv, men kan for eks gjøres gjennom en rettssak.
- Man kan se oversikt over alle bøter og dine egne bøter i grupper man er medlem i/har adminrettigheter i.
- Bøter kan settes til "betalt" når de er vekslet inn og betalt.
- Vi kan lage en total "Wall of Shame" der man har en totaloversikt over hvem i TIHLDE som har fått flest bøter.
- Bruk et artig ikon som symbol for hver bot. Online bruker vinflasker, kanskje vi kan bruke øl for eksempel?

**Comment by anderssonw** [comment]
Online bruker også ølflasker! Vi skiller på vinstraff = 100kr og ølstraff = 25kr.

Kan være en idé å kunne velge "godkjenneren" av straffene vilkårlig, ikke at det er gruppeleder.

**Comment by olros** [comment]
> Online bruker også ølflasker! Vi skiller på vinstraff = 100kr og ølstraff = 25kr.

Hmm, får se hva vi gjør. Finnes jo mange forskjellige alkoholenheter. Tror uansett at vi lager 1 enhet som gruppene selv kan bestemme verdien av.

> Kan være en idé å kunne velge "godkjenneren" av straffene vilkårlig, ikke at det er gruppeleder.

Godt innspill. Permission-systemet vårt legger ikke opp til det, men det kan bli enklere med https://github.com/TIHLDE/Lepton/issues/125. Tror uansett vi bør starte med leder for å få det opp og gå, så kan spesifikke roller heller komme senere
