### ISSUE TITLE
Offentlige profiler

### ISSUE THREAD

**Issue by Eirsteir** [TIHLDE/Kvark#281]
### Feature request

**Som bruker ønsker jeg å kunne gå til andre brukeres profiler slik at jeg kan se nyttig informasjon om andre medlemmer**

Informasjonen på profilen bør inkludere: 
- Studie og årstrinn
- Kontaktinfo (brukernavn og epost)
- Medlemsskaper 

Issue i Lepton: TIHLDE/Lepton#324

**Comment by olros** [comment]
Duplicate of #274
