### ISSUE TITLE
Kontaktinfo til gruppe i gruppeoversikt

### ISSUE THREAD

**Issue by anderssonw** [TIHLDE/Kvark#286]
### Feature request

Hadde vært veldig fint med kontaktinfo til gruppene i gruppeoversikten (https://tihlde.org/grupper/). Per nå er det noen grupper her og der som har lagt inn i sin description, men det hadde vært fint med noe a la denne flotte illustrasjonen: 

![Skjermbilde 2021-11-11 133752](https://user-images.githubusercontent.com/61270418/141299405-ee5cee72-06a1-4d46-8a8d-955d5f00242e.png)

**Comment by magsteen** [comment]
Jeg lagde noen variasjoner:

![Screenshot from 2022-01-20 17-57-32](https://user-images.githubusercontent.com/73636441/150396332-a3770f93-29ab-4b4f-ab73-362fb7ef1e21.png)
![Screenshot from 2022-01-20 18-34-42](https://user-images.githubusercontent.com/73636441/150396335-2d04dfca-aa70-4bfc-a18f-61850b174ffe.png)
![Screenshot from 2022-01-20 19-04-41](https://user-images.githubusercontent.com/73636441/150396337-d5bfaf92-213a-4f41-86ee-d1581f3b579a.png)



Hvilken liker vi best? ^_^
