### ISSUE TITLE
Navigasjon under en spesifikk gruppe i gruppeoversikt

### ISSUE THREAD

**Issue by anderssonw** [TIHLDE/Kvark#287]
### Feature request

Breadcrumbs eller liknende for navigasjon i gruppeoversikten. Hvis man velger en gruppe nå kan man bare navigere tilbake til oversikt med chrome, eller gå tilbake til gruppeoversikten via Generelt -> Gruppeoversikt

**Comment by olros** [comment]
Kan støtte denne. Bør sees i sammenheng med #272 som vil kreve en layout-endring på gruppesider for å få plass til botoversikt.
