### ISSUE TITLE
Oppdatere logo i "Ny-student"

### ISSUE THREAD

**Issue by maxschau** [tihlde/Kvark#297]
Gammel logo er fortsatt i bruk på "Ny-Student"-siden

![image](https://user-images.githubusercontent.com/49594236/98365726-1d2f6b80-2033-11eb-926b-99033037f1ca.png)

**Comment by olros** [comment]
Må snakke med Promo og få ny logoer i svg/png-format

**Comment by bjosttveit** [comment]
Logoen i banneren og på forsiden må også oppdateres, den nye offisielle logoen er litt annerledes. Den ligger i illustrator og (stor) png format i driven her: https://drive.google.com/drive/folders/122VC4JsPYP7NSIBMb34zvvOSolk6t86S?usp=sharing

![Skjermbilde 2020-11-07 113939](https://user-images.githubusercontent.com/47412359/98438926-00a43980-20ee-11eb-879f-b77019758ffd.png)
