### ISSUE TITLE
Tags på nyheter og forms

### ISSUE THREAD

**Issue by trthingnes** [TIHLDE/Kvark#300]
Legg inn støtte i frontend for tagger på nyheter og forms. Det er mulighet for at både nyheter og forms deler de samme taggene.

Som redaktør ønsker jeg å kunne opprette nye og slette gamle tagger.
Som redaktør ønsker jeg å kunne legge til en eller flere relevante tagger på nyheter eller skjemaer.

Som bruker ønsker jeg å kunne se hvilke tags som hører til en nyhet eller et skjema.
Som bruker ønsker jeg å kunne velge en tag og se nyheter/skjema som tilhører denne.

**Comment by MinhdanNg** [comment]
[TIHLDE/Lepton#355](https://github.com/TIHLDE/Lepton/issues/355)
