### ISSUE TITLE
Kommentarer på innlegg

### ISSUE THREAD

**Issue by trthingnes** [TIHLDE/Kvark#301]
Legg inn støtte for kommentarer på innlegg.

Som redaktør ønsker jeg å kunne slå av og på kommentarfeltet på nyhetssaker.
Som redaktør ønsker jeg å kunne moderere kommentarfeltet.

Som bruker ønsker jeg å kunne legge inn kommentarer på innlegg.

**Comment by MinhdanNg** [comment]
[TIHLDE/Lepton#356](https://github.com/TIHLDE/Lepton/issues/356)
