### ISSUE TITLE
Utsending av gavekort til deltagere

### ISSUE THREAD

**Issue by norgor** [TIHLDE/Kvark#334]
Som NoK-medlem har jeg lyst å sende gavekort til alle som deltar på et arrangement. Dette er for å forbedre arbeidsflyten som er manuell per dags dato.

**Comment by MartinClementz** [comment]
## Forslag
For å gjøre dette lettere for oss selv kan vi lage et pythonscript som NoK medlemmer kan laste ned. Dette scriptet kjøres lokalt på NoK medlemmet sin maskin. Denne løsningen har mange fordeler. 
* Det lett å lage og kan leveres til NoK relativt kjapt. 
* Slipper å laste opp mange vedlegg/pdfer som bruker plass i filserveren
* Mindre kompleksitet både i frontend og backend
* Arbeidsflyten til NoK vil være kjappere, fordi NoK medlemmet vil kun trenge scriptet i samme mappe som vedleggene.

Her er en god side med informasjon hvordan sende mails med python https://realpython.com/python-send-email/

**Comment by olros** [comment]
Som vi har skrevet i Lepton-issuet så er den en mulighet å bruke Abakus sitt script: https://github.com/TIHLDE/Lepton/issues/398. Problemet med det er at NoK-medlemmer ofte ikke er teknisk kompetente og dermed vil slite med å kjøre det selv.
