### ISSUE TITLE
"brake" for lange ord

### ISSUE THREAD

**Issue by Zenjjim** [tihlde/Kvark#336]
Legg til `word-break: break-all` for å unngå at lange ord ødelegger siden

![Screenshot_20201221-123349.jpg](https://user-images.githubusercontent.com/23628986/102773138-05186f00-4389-11eb-92a8-d27027b145b5.jpg)

**Comment by olros** [comment]
Good catch! `overflow-wrap: break-word` er bedre for å unngå at vanlige ord breakes istedenfor å begynne på neste linje. (Se hvordan student spres på 2 linjer i bildet)
![image](https://user-images.githubusercontent.com/31009729/102789356-54b86400-43a4-11eb-9466-d89d8ee2ba41.png)
