### ISSUE TITLE
Nye linker i "Lover"

### ISSUE THREAD

**Issue by olros** [tihlde/Kvark#339]
Noe nytt innhold i flere lover og vedtekter, link kommer

**Comment by Eirsteir** [comment]
TIHLDEs lover: https://drive.tihlde.org/index.php/s/XHSTzMdNNYkcii7
Undergruppeinstrukser: https://drive.tihlde.org/index.php/s/PFCxsydPixPT7Rk 
Styreinstruks for hovedstyret: https://drive.tihlde.org/index.php/s/6ofQZDAACYjicAS
Regler og instrukser for TIHLDE-kontoret: https://drive.tihlde.org/index.php/s/ZRJHFicjRgCT4BA
Regler og instrukser for Sosialen: https://drive.tihlde.org/index.php/s/6reZE8JAiCXDAAG
Regler og instrukser for Promo.pdf: https://drive.tihlde.org/index.php/s/RFENK6jntf82F4k
Regler og instrukser for Næringsliv og Kurs: https://drive.tihlde.org/index.php/s/koXWrtzzqmykTFP
Regler og instrukser for Index: https://drive.tihlde.org/index.php/s/noqsxJDaAs5tySG
Regler og instrukser for Drift: https://drive.tihlde.org/index.php/s/o2aKNFBNzzndnmK
Regler og instrukser for De Eldstes Raad: https://drive.tihlde.org/index.php/s/aXn6QF8BrMPkQwr
