### ISSUE TITLE
Legg inn mulighet for å ikke trenge å spesifisere utløpsdato for jobbannonser

### ISSUE THREAD

**Issue by Eirsteir** [tihlde/Kvark#367]
**Use-case**: Som admin/NoK ønsker jeg å ikke trenge å måtte spesifisere utløpsdato for jobbannonser og ønsker at denne i så fall skal settes til "Fortløpende".

~~Dette feltet kan lagres som `null`, som er en lovlig verdi for feltet i backend.~~

**Comment by olros** [comment]
@Eirsteir  Tror ikke det er den beste løsningen siden NoK da må inn og slette annonser når de skal skjules. Tror en bedre løsning er et boolean felt i databasen som sier om det er fortløpende frist eller ikke.

**Comment by Eirsteir** [comment]
Ser hva du mener, men jeg tror det er bedre om vi legger til et felt som heter `visibleTo` / `removal_date` som angir utløpsdato for annonsen (når den skal fjernes fra nettsiden) på samme måte som vi bruker `expired` idag, bare at vi bruker dette feltet istedenfor `deadline` til å gjøre det. Hva tror du?

**Comment by olros** [comment]
Tror det er bedre med et påkrevd tidsfelt og et boolean, ift at du må velge mellom å fylle ut en av dem. Da slipper man også å håndtere hvis man fyller ut begge to

**Comment by Eirsteir** [comment]
Det blir i bunn og grunn det samme. Men i den løsningen vil man bruke søknadsfristen til å angi når annonsen skal fjernes og det er ikke det samme. Da vil vi bruke søknadsfristen til både å angi når den skal fjernes og når fristen for å søke er. 

Mener det da er lettere å forholde seg til å droppe å sette en dato for søknadsfrist og heller sette en dato den fjernes. Hvis man fyller ut begge to så bruker vi alltid datoen for når den skal fjernes til å angi når den er utløp.

**Comment by olros** [comment]
Vel, jeg tenker egt at det er akkurat det samme. Hvis det fortløpende ansettelser frem til annonsen fjernes så betyr det også at siste frist for å søke er idet annonsen fjernes. Forskjellen mellom annonsene ved en checkbox blir dermed kun at vi endrer fra "Søknadsfrist" til "Fortløpende opptak frem til".

Ser ikke helt et usecase hvor det er ønskelig at annonsen skal skjules enten før eller etter søknadsfristen?

**Comment by Eirsteir** [comment]
Da går det litt på hvilken som er lettest å forholde seg til, forstå og implementere. 

Forslaget ditt gjør at vi slipper å ha enkelte sjekker, men betydningen av deadlinen avhenger av om det er fortløpende opptak eller ikke. Det er ikke optimalt databasedesign. Her bruker frontend deadlinen som søknadsfrist hvis ikke flagget er satt, backend bruker fortsatt deadline til å bestemme om den er utløpt eller ikke. 

Hvis vi velger å ha et felt for utløpsdato så trenger ikke deadlinen å være satt, slik du sier med en checkbox. Da vil vi ha et klart skille på om det er søknadsfrist/løpende opptak og når annonsen skal tas ned. Men som du også sier bør det legges inn sjekker i backend så ikke annonsen skjules før eller etter søknadsfristen, om enn minimalt. Her forholder frontend seg kun til deadlinen ved fremvisning, backend bestemmer om den er utløpt eller ikke. Evt ha "Søknadsfrist" vs "Utløpsdato" ved en checkbox. 

Jeg tror det blir lettere å forholde seg til og bedre design at vi har ett felt for søknadsfrist og ett for utløpsdato, og at det er løpende opptak hvis søknadsfristen ikke er satt.

**Comment by olros** [comment]
Tenker vi får ta en diskusjon på neste møte jeg :)

**Comment by Eirsteir** [comment]
Good call :)

**Comment by olros** [comment]
Closed by #388
