### ISSUE TITLE
Feil postnummer under tihlde.org/om/kontakt-oss/

### ISSUE THREAD

**Issue by Eirsteir** [TIHLDE/Kvark#39]
Her skal det stå *7034*, ikke *7491*

![image](https://user-images.githubusercontent.com/35424810/111467076-533cd480-8724-11eb-82fd-fc8b03a7a471.png)

**Comment by olros** [comment]
Bare å oppdatere siden i pages. Dette er ikke hardkodet inn i Kvark

**Comment by olros** [comment]
https://tihlde.org/om/kontakt-oss/ Oppdaterte
