### ISSUE TITLE
Skrive TIHLDE med CAPS-LOCK

### ISSUE THREAD

**Issue by maxschau** [TIHLDE/Kvark#45]
![image](https://user-images.githubusercontent.com/49594236/112017296-c3d16000-8b2d-11eb-9d8f-e6dba59dd89c.png)

Dette MÅ skrives med store bokstaver!!!!

**Comment by olros** [comment]
Fikset når man er inne på TIHLDE-siden, typ /om/tihlde/. Ikke hvis man er på underside av TIHLDE, typ /om/tihlde/undergrupper/.

Closer siden det ikke er viktig ift hvor tungvint det er
