### ISSUE TITLE
Panel for å legge til/fjerne medlemmer i de ulike gruppene

### ISSUE THREAD

**Issue by maxschau** [TIHLDE/Kvark#54]
Nå som vi er i ferd med å implementere visning av de ulike gruppemedlemmene burde vi også ha et panel for undergruppe-lederne å legge til/fjerne medlemmer i databasen. Altså at de skal kunne oppdatere membership-entiteten i databasen.

Dette vil gjøre det svært enkelt for lederne å sørge for at oversikten over medlemmene er korrekt til enhver tid.

**Comment by olros** [comment]
Duplikat av #8 😅
