### ISSUE TITLE
Digitalt fotoalbum

### ISSUE THREAD

**Issue by Eirsteir** [TIHLDE/Kvark#66]
User stories: 
- Som ny søker til linjeforeningene ønsker jeg å se gjennom bilder i et digitalt fotoalbum slik at jeg kan få et bedre innblikk i hvordan studiet/linjeforeningen er.
- Som medlem ønsker jeg å se gjennom bilder i et digitalt fotoalbum slik at jeg kan se gjennom bilder fra gamle arrangementer jeg har deltatt på.

Opprett et digital fotoalbum med bilder fra TIHLDEs arrangementer o.l. gjennom årene. Det
ligger mye forskjellig på FaceBook og Google Drive som burde samles og presenteres på f.eks. nettsiden.
Spesielt viktig for nye søkere som loker på nettsiden. Gamle medlemmer kan også mimre tilbake.

**Comment by callumgran** [comment]
Til dette tenker jeg at det er naturlig å bruke MUI sin egen image list: https://mui.com/components/image-list/.

**Comment by olros** [comment]
Vi kan gjøre dette sammen slik at du lærer deg hooks'ene :)

Ift til design av sidene er Masonry-listen en veldig fin start. Det som også må avklares er:
- Visning av et spesifikt bilde (ved klikk på et bilde i Masonry-listen)
- Hvordan skal listen over album se ut? Her bør det komme inn et søkefelt også.
- Hvordan skal det se ut der admins kan lage nye album, laste opp bilder til albumet og evt knytte det til et arrangement?

**Comment by callumgran** [comment]
[DigitaltFotoAlbum.txt](https://github.com/TIHLDE/Kvark/files/7460861/DigitaltFotoAlbum.txt)

**Comment by callumgran** [comment]
Utføring av digitalt fotoalbum:
-	Bruke en side som ligner på pages for å finne forskjellige album:
	-	Dette kan deles opp i år, deretter måneder og deretter arrangementene.
	-	Det kan også deles opp i sosiale arrangement, bedpresser og annet, men år burde være hoved oppdelingen.
	-	Tittelen skal selvsagt vise hvilket arrangement og hvilket år.

-	Visuelt burde det være mulig å vise bilder i forskjellige formater, uten at det ser rart ut:
	-	Det er viktig at bildene ikke må "croppes" til en viss størrelse for å vises, slik at hele bildene vises.
		-	Derfor er MUI sin masonry image list bra.
	-	Bildene burde ha en tittel under eller nederst over bildet som beskriver hva bildet er, denne proppen kan være valgfri.
	-	Bildene burde også være mulig å trykke på slik at de blir forstørret.
		-	Når man åpner bildet burde dette også vise en beskrivelse, denne proppen kan være valgfri.
	-	Bildene burde komme opp slik at de bildene som er tatt tidligst på arrangementet burde komme først i feeden, altså ascending order.

-	Søk etter bilder:
	-	Her kan eventuelt alt-teksten brukes som en pekepinne slik at alle bilder ikke trenger den valgfrie tittel proppen.
	
-	Knytting av arrangementer til album:
	-	Slik jeg forstår det så lagrer vi alle tidligere arrangementer, derfor så kan vi bruke id'ene til arrangementene for å knytte de sammen.
	-	Dette gjør også at man kan implentere bilder lettere inn i nye arrangementer med samme arrangør/tema i fremtiden.
		- Vi kunne laget en måte å eksportere/importere et album i mini-format til fremtidige arrangementer.
		
-	Opplasting av bilder:
	-	Slik opplastningsfunksjonen for bilder er i dag, så kan kun admins bruke den ut i fra min kunnskap.
		-	Dermed kunne vi tatt denne komponenten og implementert den i en album-admin side som kun kommer om man er admin.
		-	I tillegg til dette synes jeg det burde være åpent for at medlemmer skal kunne sende inn bilder på sosiale arrangementer
			som deretter kunne blitt godtatt av en admin.

-	Skisse:
	-	Lager en liten nettside som kan vise hvordan jeg tenker at det burde se ut til tirsdagsmøtet neste uke.

**Comment by olros** [comment]
> * Bruke en side som ligner på pages for å finne forskjellige album:
>   
>   * Dette kan deles opp i år, deretter måneder og deretter arrangementene.
>   * Det kan også deles opp i sosiale arrangement, bedpresser og annet, men år burde være hoved oppdelingen.
>   * Tittelen skal selvsagt vise hvilket arrangement og hvilket år.

Album må ikke være knyttet til et arrangement, så det bør ikke være hovedfokus ved visning. Tenker man heller kan ha en link til arrangementet hvis det er knyttet til album fra inne i et album. Ulempen med å måtte klikke seg inn på år -> måned osv er at det kan være vanskelig å finne album hvis du ikke vet nøyaktig når det var. Fra backend får man også bare ut en liste med albumene, så tenker det holder å vise den listen kronologisk der nyeste album er øverts (altså samme rekkefølge som kommer fra backend).

> * Visuelt burde det være mulig å vise bilder i forskjellige formater, uten at det ser rart ut:
>   
>   * Det er viktig at bildene ikke må "croppes" til en viss størrelse for å vises, slik at hele bildene vises.
>     
>     * Derfor er MUI sin masonry image list bra.
>   * Bildene burde ha en tittel under eller nederst over bildet som beskriver hva bildet er, denne proppen kan være valgfri.
>   * Bildene burde også være mulig å trykke på slik at de blir forstørret.
>     
>     * Når man åpner bildet burde dette også vise en beskrivelse, denne proppen kan være valgfri.
>   * Bildene burde komme opp slik at de bildene som er tatt tidligst på arrangementet burde komme først i feeden, altså ascending order.

Enig! Hva tror du er best av å vise enkeltbilder etter klikk på en egen side, eller som en "popup" der resten av siden blir mørkere? Jeg tror kanskje det siste er best.

> * Søk etter bilder:
>   
>   * Her kan eventuelt alt-teksten brukes som en pekepinne slik at alle bilder ikke trenger den valgfrie tittel proppen.

Du trenger ikke tenke på hvordan man skal søke, det fikser backend. Det du må tenke på er hvor selve søkefeltet skal ligge. Det kan for eksempel ligge til høyre på siden slik som på arrangementer- og karriere-siden.

> * Knytting av arrangementer til album:
>   
>   * Slik jeg forstår det så lagrer vi alle tidligere arrangementer, derfor så kan vi bruke id'ene til arrangementene for å knytte de sammen.
>   * Dette gjør også at man kan implentere bilder lettere inn i nye arrangementer med samme arrangør/tema i fremtiden.

Du trenger heller ikke her å tenke på hvordan selve lagringen av tilknytning mellom arrangement og album skal skje, backend fikser det. Det du må tenke på er hvordan bruker kan velge hvilket arrangement albumet skal høre til. Det kan for eksempel skje gjennom en select-boks eller autocomplete slik som i brukeradmin der admins kan søke etter brukere.

>     
>     * Vi kunne laget en måte å eksportere/importere et album i mini-format til fremtidige arrangementer.

Hva mener du med dette? ^

> * Opplasting av bilder:
>   
>   * Slik opplastningsfunksjonen for bilder er i dag, så kan kun admins bruke den ut i fra min kunnskap.
>     
>     * Dermed kunne vi tatt denne komponenten og implementert den i en album-admin side som kun kommer om man er admin.

Vi har en egen opplastnings-komponent ja som kan legges inn i alle skjemaer. Backend har laget en smart måte for oss å sende inn en liste med nye bilder, kan komme tilbake til dette. Det som her egt må tenkes på er hvor denne opplastnings-komponenten skal plasseres.

>     * I tillegg til dette synes jeg det burde være åpent for at medlemmer skal kunne sende inn bilder på sosiale arrangementer
>       som deretter kunne blitt godtatt av en admin.

Kul tanke! Det er ikke tenkt på før, men kan absolutt legges til senere. Da må backend også gjøre endringer, så foreslår at du lager et eget issue på dette slik at det huskes til senere. Så fokuserer vi på det backend har til nå i denne omgangen.
