### ISSUE TITLE
Skille sosiale arrangementer og NoK sine arrangement i kalenderen

### ISSUE THREAD

**Issue by Eirsteir** [TIHLDE/Kvark#67]
For å enklere se hvem som arrangerer hva i kalenderen bør det brukes fargekoder så det er mulig å skille mellom dem.

**Comment by olros** [comment]
Her må vel lepton først oppdatere events med felt for hvem som er arrngør på events?

**Comment by Eirsteir** [comment]
Dét, eller bare ta det på kategorier

**Comment by olros** [comment]
Ja, tror kategorier er en dårlig idé siden de er dynamiske. Stemmer for å fjerne kategorier og prioritet fra lepton og erstatte med arrangør

**Comment by Eirsteir** [comment]
Vi må kunne skille på bedpres, kurs og sosialt så vi trenger litt mer info enn kun arrangør, men vi kan diskutere nærmere på mandag.
