### ISSUE TITLE
Endre knappen på kokeboka

### ISSUE THREAD

**Issue by callumgran** [TIHLDE/Kvark#720]
### Refactor suggestion

Jeg synes knappen vi har for å sende ny kok på kokeboka ser litt uryddig ut og den behøver ikke sin egen "rad". Kunne denne knappen bli endret slik at den ser ut som knappen for å legge til et nytt galleri?
![image](https://user-images.githubusercontent.com/89872274/203965865-c4d8e548-5e07-4407-987d-f3b9484c525b.png)
![image](https://user-images.githubusercontent.com/89872274/203965905-96c392b8-747b-479c-aae5-b1585c0c103c.png)

**Comment by martcl** [comment]
Den kan godt komme på samme rad som tittelen, god idee! Men jeg tenker at den bør skille seg ut fra galleri-knappen, siden de gjør vidt forskjellige ting. Kokebok-knappen tar deg av nettsiden, mens galleri-knappen holder deg pp nettsiden. Men mens man flytter knappen, kan man godt legge på et icon på knappen som sier at den tar deg inn i standard mailapp
