### ISSUE TITLE
Det mangler en 'r' i Turtorial

### ISSUE THREAD

**Issue by bjosttveit** [TIHLDE/Kvark#76]
![bilde](https://user-images.githubusercontent.com/47412359/116244987-c5afc400-a768-11eb-93d2-564b751ecfac.png)
Gruppen heter egentlig:
![bilde](https://user-images.githubusercontent.com/47412359/116245082-db24ee00-a768-11eb-969e-d89e8fe05c70.png)

**Comment by Zenjjim** [comment]
Fin catch @bjosttveit. Da skal det være fikset.
![image](https://user-images.githubusercontent.com/23628986/116256810-d0bc2180-a773-11eb-9c08-59e88a74f81b.png)
