### ISSUE TITLE
Lag gruppe-admin

### ISSUE THREAD

**Issue by olros** [TIHLDE/Kvark#8]
Lag admin-side for spesifikke grupper under urlen: `/admin/grupper/<gruppe-id>/`. Kun personer som har tilgang til å endre gruppen bør få lov til å se siden.

Muligheter på siden:
• Endre gruppe-detaljer
• Se medlemmer og fjern/legg til dem
• Endre stilling på medlemmer fra/til leder
Oversikt over alle grupper i admin gjøres i annen pr

**Comment by maxschau** [comment]
Jeg forsøker å designe dette i Figma. Feel free to join
