### ISSUE TITLE
Sortering av kokebok 

### ISSUE THREAD

**Issue by simonaardal** [TIHLDE/Kvark#98]
Hadde vært noice med en sortering/filtreringsfunksjon der det står "Fag:" (kanskje gjøre om teksten til en knapp), sånn at ikke fagene står i random rekkefølge nedover siden. Kansje sortert på fagkode eller lignende.

**Comment by Zenjjim** [comment]
Dette kan løses ved å bruke [MUI-tables](https://material-ui.com/components/tables/#sorting-amp-selecting)
